import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('textbox', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Login' }).fill('jan');
  await page.getByRole('textbox', { name: 'Hasło' }).click();
  await page.getByRole('textbox', { name: 'Hasło' }).fill('1234');
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Zaloguj' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('test');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('test');
  await page.getByRole('button', { name: 'Utwórz projekt' }).click();
  await page.getByRole('button', { name: 'Edytuj' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('test2');
  await page.locator('input[type="text"]').click();
  await page.getByText('test').click();
  await page.getByText('test').fill('test2');
  await page.getByRole('button', { name: 'Edytuj projekt' }).click();
  await page.getByRole('button', { name: 'Wybierz' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('test');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('test');
  await page.getByRole('combobox').first().selectOption('low');
  await page.getByRole('button', { name: 'Dodaj Historyjkę' }).click();
  await page.getByRole('button', { name: 'Edytuj' }).click();
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('test2');
  await page.getByText('test').click();
  await page.getByText('test').fill('test2');
  await page.getByRole('combobox').first().selectOption('high');
  await page.getByRole('combobox').nth(1).selectOption('doing');
  await page.getByRole('button', { name: 'Edytuj historyjkę' }).click();
  await page.getByRole('button', { name: 'Wybierz' }).click();
  await page.getByRole('button', { name: 'Wybierz' }).click();
  await page.getByRole('button', { name: 'Wybierz' }).click();
  await page.getByRole('textbox', { name: 'Nazwa zadania' }).click();
  await page.getByRole('textbox', { name: 'Nazwa zadania' }).fill('test');
  await page.getByRole('textbox', { name: 'Opis zadania' }).click();
  await page.getByRole('textbox', { name: 'Opis zadania' }).fill('test');
  await page.getByRole('textbox', { name: 'Szacowany czas (np. 2h)' }).click();
  await page.getByRole('textbox', { name: 'Szacowany czas (np. 2h)' }).fill('wh');
  await page.getByRole('combobox').selectOption('low');
  await page.getByRole('textbox', { name: 'Szacowany czas (np. 2h)' }).click();
  await page.getByRole('textbox', { name: 'Szacowany czas (np. 2h)' }).fill('2h');
  await page.getByRole('button', { name: 'Dodaj zadanie' }).click();
  await page.getByRole('button', { name: 'Edytuj' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('test2');
  await page.getByText('test').click();
  await page.getByText('test').fill('test2');
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('4h');
  await page.getByRole('combobox').nth(1).selectOption('doing');
  await page.getByRole('combobox').first().selectOption('high');
  await page.getByRole('button', { name: 'Zapisz zmiany' }).click();
  await page.getByRole('button', { name: 'Szczegóły' }).click();
  await page.getByLabel('Przypisz osobę:-- Wybierz').selectOption('2');
  await page.getByRole('button', { name: 'Oznacz jako zakończone' }).click();
  await page.getByRole('button', { name: 'Zobacz Kanban' }).click();
  await page.getByRole('button', { name: 'Usuń' }).click();
  await page.goto('http://localhost:5173/home');
  await page.getByRole('button', { name: 'Wybierz' }).click();
  await page.getByRole('button', { name: 'Usuń' }).click();
  await page.getByRole('button', { name: 'Usuń' }).click();
});